# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpK9cboiyhW9nUYW1oomjsbAromHI-Vp
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("estados_bruto.xml.csv")
df.head()

df.info()

df.describe()

dados = df[['PIB_percapita', 'Pop_est_2009']]
dados = dados.dropna()
dados.head()

scaler = StandardScaler()
dados_normalizados = scaler.fit_transform(dados)

inercia = []

for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(dados_normalizados)
    inercia.append(kmeans.inertia_)

plt.figure()
plt.plot(range(1, 11), inercia)
plt.xlabel("Número de clusters")
plt.ylabel("Inércia")
plt.title("Método do Cotovelo")
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(dados_normalizados)

df_modelo = dados.copy()
df_modelo['Cluster'] = clusters
df_modelo.head()

plt.figure()
plt.scatter(
    df_modelo['PIB_percapita'],
    df_modelo['Pop_est_2009'],
    c=df_modelo['Cluster']
)
plt.xlabel("PIB per capita")
plt.ylabel("População estimada")
plt.title("Agrupamento de Municípios por Indicadores Econômicos")
plt.show()

















